### ISSUE TITLE
日記情報一覧取得APIのエンドポイント

### ISSUE THREAD

**Issue by Neru-Neru** [taisey/Blockory#1]
# api-list.md内
日記情報一覧取得 GET DiaryInfo/{year, month, day}と準タイトルに書いてありますが、その下の例では`GET AllDiaryInfoMonth/?year=2022&month=2&day=3`となっています。
日記情報登録 POST /DiaryInfoとなっていて重複しているため、日記情報一覧取得に対応する正しいエンドポイントは`AllDiaryInfoMonth`でOKですか？
(参考：https://github.com/taisey/Blockory/blob/main/backend/api-list.md#%E6%97%A5%E8%A8%98%E6%83%85%E5%A0%B1%E4%B8%80%E8%A6%A7%E5%8F%96%E5%BE%97get-diaryinfoyear-month-day)

**Comment by taisey** [comment]
> 日記情報一覧取得 GET DiaryInfo/{year, month, day}と準タイトルに書いてありますが、その下の例ではGET AllDiaryInfoMonth/?year=2022&month=2&day=3となっています。

api-listに記載されているGET DiaryInfo/{year, month, day}の例が間違っていますね。
誤：GET AllDiaryInfoMonth/?year=2022&month=2&day=3
正：GET DiaryInfo/?year=2022&month=2&day=3
api-listを訂正しておきます。

>日記情報登録 POST /DiaryInfoとなっていて重複しているため、日記情報一覧取得に対応する正しいエンドポイントはAllDiaryInfoMonthでOKですか？

日記情報登録と日記情報一覧取得は同一のエンドポイントを使用します。
メゾッド（GETとPOST）で2つのAPIを使い分けてください。

**Comment by Neru-Neru** [comment]
Okay, I'll correspond it.
